export const countriesList = [
    "Sénégal",
    "Afrique du Sud",
    "Algérie",
    "Angola",
    "Bénin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroun",
    "Cap-Vert",
    "République centrafricaine",
    "Comores",
    "Congo",
    "Côte d'Ivoire",
    "Djibouti",
    "Égypte",
    "Érythrée",
    "Eswatini",
    "Éthiopie",
    "Gabon",
    "Gambie",
    "Ghana",
    "Guinée",
    "Guinée-Bissau",
    "Guinée équatoriale",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libye",
    "Madagascar",
    "Malawi",
    "Mali",
    "Maroc",
    "Maurice",
    "Mauritanie",
    "Mozambique",
    "Namibie",
    "Niger",
    "Nigeria",
    "Ouganda",
    "Rwanda",
    "São Tomé-et-Principe",
    "Seychelles",
    "Sierra Leone",
    "Somalie",
    "Soudan",
    "Soudan du Sud",
    "Tanzanie",
    "Tchad",
    "Togo",
    "Tunisie",
    "Zambie",
    "Zimbabwe",
    // Add european/common countries used elsewhere
    "France",
    "Espagne",
    "Italie",
    "Allemagne",
    "États-Unis",
];

export const nationalityByCountry: Record<string, string> = {
    "Sénégal": "sénégalaise",
    "Afrique du Sud": "sud-africaine",
    "Algérie": "algérienne",
    "Angola": "angolaise",
    "Bénin": "béninoise",
    "Botswana": "botswanaise",
    "Burkina Faso": "burkinabè",
    "Burundi": "burundaise",
    "Cameroun": "camerounaise",
    "Cap-Vert": "cap-verdienne",
    "République centrafricaine": "centrafricaine",
    "Comores": "comorienne",
    "Congo": "congolaise",
    "Côte d'Ivoire": "ivoirienne",
    "Djibouti": "djiboutienne",
    "Égypte": "égyptienne",
    "Érythrée": "érythréenne",
    "Eswatini": "eSwatinienne",
    "Éthiopie": "éthiopienne",
    "Gabon": "gabonaise",
    "Gambie": "gambienne",
    "Ghana": "ghanéenne",
    "Guinée": "guinéenne",
    "Guinée-Bissau": "guinéenne-bissau",
    "Guinée équatoriale": "guinéenne-éq",
    "Kenya": "kenyane",
    "Lesotho": "lesothane",
    "Liberia": "libérienne",
    "Libye": "libyenne",
    "Madagascar": "malgache",
    "Malawi": "malawienne",
    "Mali": "malienne",
    "Maroc": "marocaine",
    "Maurice": "mauricienne",
    "Mauritanie": "mauritanienne",
    "Mozambique": "mozambicaine",
    "Namibie": "namibienne",
    "Niger": "nigérienne",
    "Nigeria": "nigériane",
    "Ouganda": "ougandaise",
    "Rwanda": "rwandaise",
    "São Tomé-et-Principe": "santoméenne",
    "Seychelles": "seychelloise",
    "Sierra Leone": "sierra-léonienne",
    "Somalie": "somalienne",
    "Soudan": "soudanaise",
    "Soudan du Sud": "soudanaise",
    "Tanzanie": "tanzanienne",
    "Tchad": "tchadienne",
    "Togo": "togolaise",
    "Tunisie": "tunisienne",
    "Zambie": "zambienne",
    "Zimbabwe": "zimbabwéenne",
    "France": "française",
    "Espagne": "espagnole",
    "Italie": "italienne",
    "Allemagne": "allemande",
    "États-Unis": "américaine",
};

export function getNationality(country?: string | null): string {
    if (!country) return '';
    // Return mapped nationality when available, otherwise return the country name
    return nationalityByCountry[country] || country;
}
